// <auto-generated />
using DANLUIS_AP1_P1.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DANLUIS_AP1_P1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20261005162143_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DANLUIS_AP1_P1.Models.Modelo1", b =>
                {
                    b.Property<int>("Modelo1Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Modelo1Id"));

                    b.HasKey("Modelo1Id");

                    b.ToTable("Modelo1s");
                });
#pragma warning restore 612, 618
        }
    }
}
